# cargo-deny configuration (R5: advisories, licenses, bans, sources).
# The workspace has zero external dependencies, so these checks are structural
# guards that keep it that way.

[advisories]
version = 2
yanked = "deny"

[licenses]
version = 2
allow = ["Apache-2.0", "MIT", "Apache-2.0 WITH LLVM-exception", "BSD-3-Clause", "ISC", "Unicode-3.0", "Zlib", "BSD-2-Clause", "CC0-1.0", "0BSD", "MPL-2.0", "CDLA-Permissive-2.0"]
confidence-threshold = 0.8

[bans]
multiple-versions = "warn"
wildcards = "deny"
highlight = "all"
deny = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
