//! Repo automation tasks. `cargo xtask <task>` mirrors what CI runs.
//!
//! `spec-check` (R7): the parameter table in SPEC.md must byte-equal the
//! table generated from `configs/`, and the kernel tolerance table in
//! docs/kernels.md must match the tolerance registry.

#![deny(missing_docs)]
#![cfg_attr(test, allow(clippy::unwrap_used, clippy::expect_used))]

use rhizome_core::config::Config;
use rhizome_core::params;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn repo_root() -> PathBuf {
    let mut p = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    while !p.join("Cargo.lock").exists() {
        p.pop();
    }
    p
}

fn load_configs(root: &Path) -> Vec<(String, Config)> {
    let mut names = vec!["test-s", "test-m", "test-l", "edge", "standard", "flagship"];
    names.sort_unstable();
    names
        .into_iter()
        .map(|name| {
            let path = root.join("configs").join(format!("{name}.toml"));
            let src = std::fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("spec-check: read {}: {e}", path.display()));
            let cfg = Config::from_toml_str(name, &src)
                .unwrap_or_else(|e| panic!("spec-check: parse {}: {e}", path.display()));
            (name.to_string(), cfg)
        })
        .collect()
}

fn generated_params_table(root: &Path) -> String {
    let configs = load_configs(root);
    let rows: Vec<(String, rhizome_core::config::ModelConfig)> = configs
        .iter()
        .map(|(n, c)| (n.clone(), c.model.clone()))
        .collect();
    params::markdown_table(&rows)
}

/// Replace the region between `begin`/`end` markers in `doc` with `generated`.
fn splice(doc: &str, begin: &str, end: &str, generated: &str) -> (String, String, bool) {
    let bi = doc
        .find(begin)
        .unwrap_or_else(|| panic!("missing marker {begin}"));
    let after_b = &doc[bi + begin.len()..];
    let ei = after_b
        .find(end)
        .unwrap_or_else(|| panic!("missing end marker {end}"));
    let current = &after_b[..ei];
    let mut out = String::new();
    out.push_str(&doc[..bi + begin.len()]);
    out.push('\n');
    out.push_str(generated.trim_end());
    out.push('\n');
    out.push_str(end);
    out.push_str(&after_b[ei + end.len()..]);
    let changed = current.trim() != generated.trim();
    (out, current.to_string(), changed)
}

fn spec_check(write: bool) -> i32 {
    let root = repo_root();
    let spec_path = root.join("SPEC.md");
    let spec = std::fs::read_to_string(&spec_path)
        .unwrap_or_else(|e| panic!("spec-check: read SPEC.md: {e}"));
    let table = generated_params_table(&root);
    let (new_spec, _current, params_changed) = splice(
        &spec,
        "<!-- params:begin (generated by `rhizome params --all --format=markdown`; do not edit) -->",
        "<!-- params:end -->",
        &table,
    );
    let kernels_path = root.join("docs/kernels.md");
    let kernels = std::fs::read_to_string(&kernels_path)
        .unwrap_or_else(|e| panic!("spec-check: read docs/kernels.md: {e}"));
    // Kernel tolerance table check: every op listed in the registry must have
    // a tolerance row. The registry itself lands with rhizome-ops (M1); the
    // structural check runs now.
    let op_lines: Vec<&str> = kernels
        .lines()
        .filter(|l| l.starts_with("| op/") || l.starts_with("| core/") || l.starts_with("| seq/"))
        .collect();
    if op_lines.is_empty() {
        println!("spec-check: FAIL docs/kernels.md has no tolerance rows");
        return 1;
    }
    if params_changed {
        if write {
            std::fs::write(&spec_path, new_spec).expect("write SPEC.md");
            println!("spec-check: UPDATED SPEC.md parameter table");
        } else {
            println!("spec-check: FAIL SPEC.md parameter table is stale");
            println!("--- expected (generated) ---\n{}\n--- rerun with `cargo xtask spec-check --write` to update ---", table.trim_end());
            return 1;
        }
    } else {
        println!(
            "spec-check: ok (params table current, {} kernel tolerance rows)",
            op_lines.len()
        );
    }
    0
}

fn main() {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let mut code = 0;
    match args.first().map(String::as_str) {
        Some("spec-check") => {
            code = spec_check(args.get(1).map(String::as_str) == Some("--write"));
        }
        Some("ci") => {
            // Print the exact commands CI runs; useful locally.
            let mut msg = String::new();
            writeln!(msg, "cargo fmt --all -- --check").unwrap();
            writeln!(msg, "cargo clippy --workspace --all-targets --features \"cpu serve-http serve-grpc deterministic\" -- -D warnings").unwrap();
            writeln!(
                msg,
                "cargo test --workspace --features \"cpu serve-http serve-grpc deterministic\""
            )
            .unwrap();
            writeln!(msg, "cargo doc --no-deps --workspace").unwrap();
            writeln!(msg, "cargo xtask spec-check").unwrap();
            print!("{msg}");
        }
        Some(other) => {
            eprintln!("xtask: unknown task {other:?}");
            code = 2;
        }
        None => {
            eprintln!("usage: cargo xtask <ci|spec-check [--write]>");
            code = 2;
        }
    }
    std::process::exit(code);
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn splice_replaces_region() {
        let doc = "a\n<!-- b -->\nold\n<!-- e -->\nz";
        let (out, cur, changed) = splice(doc, "<!-- b -->", "<!-- e -->", "new");
        assert!(changed);
        assert!(cur.contains("old"));
        assert!(out.contains("<!-- b -->\nnew\n<!-- e -->"));
        let (.., changed2) = splice(&out, "<!-- b -->", "<!-- e -->", "new");
        assert!(!changed2);
    }

    #[test]
    fn generated_table_is_stable() {
        let root = repo_root();
        let t1 = generated_params_table(&root);
        let t2 = generated_params_table(&root);
        assert_eq!(t1, t2);
        assert!(t1.contains("approx_total_params"));
    }
}
